# Generated by Django 3.2.8 on 2022-02-26 11:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 26, 11, 8, 35, 992630, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
