# Generated by Django 3.2.8 on 2022-02-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_contactus_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='Email',
            field=models.EmailField(max_length=122),
        ),
    ]
